version: '3'

services:
  customer-service:
    build:
      context: ./Customer_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=db_Customer_service
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}

  order-service:
    build: .  
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:orderservice
      SPRING_DATASOURCE_DRIVERClassName: org.h2.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  product-service:  
    build: .  
    context: product-service  
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:productservice  
      SPRING_DATASOURCE_DRIVERClassName: org.h2.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db2:
    image: 1000kit/h2:latest
    ports:
      - "9092:9092"

  user-interface:
    build:
      context: ./ecom_ui
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_USER=root
      - DJANGO_DB_NAME=db_User_Interface
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}

  notification-service:
    build:
      context: ./Notification_service
    ports:
      - "8003:80"
    depends_on:
      - rabbitmq
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_USER=root
      - DJANGO_DB_NAME=db_Notification_service
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mydatabase

  volumes:
    order-service-data:/var/lib/h2/orderservice