apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-app-service
  namespace: demo-ns
spec:
  selector:
    app: complete-production-e2e-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080