apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-app-service
  namespace: demo-ns
spec:
  selector:
    app: complete-production-e2e-app
  type: NodePort
  ports:
    - port: 9595
      targetPort: 9595
      nodePort: 30111